package com.example.bankomatsimulator.currencyresponse

import com.example.bankomatsimulator.currencyresponse.valutes.*

data class Valute(
    val AED: AED,
    val AMD: AMD,
    val AUD: AUD,
    val AZN: AZN,
    val BGN: BGN,
    val BRL: BRL,
    val BYN: BYN,
    val CAD: CAD,
    val CHF: CHF,
    val CNY: CNY,
    val CZK: CZK,
    val DKK: DKK,
    val EGP: EGP,
    val EUR: EUR,
    val GBP: GBP,
    val GEL: GEL,
    val HKD: HKD,
    val HUF: HUF,
    val IDR: IDR,
    val INR: INR,
    val JPY: JPY,
    val KGS: KGS,
    val KRW: KRW,
    val KZT: KZT,
    val MDL: MDL,
    val NOK: NOK,
    val NZD: NZD,
    val PLN: PLN,
    val QAR: QAR,
    val RON: RON,
    val RSD: RSD,
    val SEK: SEK,
    val SGD: SGD,
    val THB: THB,
    val TJS: TJS,
    val TMT: TMT,
    val TRY: TRY,
    val UAH: UAH,
    val USD: USD,
    val UZS: UZS,
    val VND: VND,
    val XDR: XDR,
    val ZAR: ZAR
)